CREATE TABLE USUARIO (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(255),
    senha VERCHAR(255),
    ativo BOOLEAN DEFAULT TRUE,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE RECEITA(
    id SERIAL PRIMARY KEY,
    nome VARCHAR (255),
    ingredientes TEXT NOT NULL,
    instrucoes TEXT NOT NULL,
    tempo_preparo_minutos INTEGER NOT NULL,
    usuario_id INTEGER NOT NULL REFERENCIES USUARIO(id) ON DELETE CASCADE
    );